-- Adım 1: Yeni enum değerleri ekle (ayrı transaction)
ALTER TYPE "KdvType" ADD VALUE IF NOT EXISTS 'KDV_191';
ALTER TYPE "KdvType" ADD VALUE IF NOT EXISTS 'KDV_391';
ALTER TYPE "KdvType" ADD VALUE IF NOT EXISTS 'ISLETME_GELIR';
ALTER TYPE "KdvType" ADD VALUE IF NOT EXISTS 'ISLETME_GIDER';
