import {
  Banknote,
  Bell,
  BookCheck,
  Bot,
  BriefcaseBusiness,
  Building2,
  CalendarCheck,
  Camera,
  CheckCircle2,
  ClipboardList,
  FileArchive,
  FileCheck2,
  FileText,
  FolderOpen,
  Inbox,
  Landmark,
  LineChart,
  Mail,
  ReceiptText,
  Scale,
  ShieldCheck,
  UploadCloud,
  Users,
} from 'lucide-react-native';
import type { ModuleColor } from './theme';

export type AppAudience = 'advisor' | 'taxpayer';
export type ModuleStatus = 'live' | 'mobile-ready' | 'prep';
export type ModulePriority = 'high' | 'medium' | 'low';

export type MobileModule = {
  id: string;
  title: string;
  subtitle: string;
  group: string;
  audience: AppAudience;
  portalPath?: string;
  apiPath?: string;
  status: ModuleStatus;
  priority: ModulePriority;
  icon: any;
};

export const advisorModules: MobileModule[] = [
  {
    id: 'dashboard',
    title: 'Ofis özeti',
    subtitle: 'Günlük iş yükü, bildirimler ve hızlı durum.',
    group: 'Ana akış',
    audience: 'advisor',
    portalPath: '/panel',
    apiPath: '/mobile/bootstrap',
    status: 'mobile-ready',
    priority: 'high',
    icon: LineChart,
  },
  {
    id: 'moren-ofis',
    title: 'Moren Ofis AI',
    subtitle: 'ARDA, DENİZ ve ekip ile yazılı/sesli çalışma.',
    group: 'AI ekip',
    audience: 'advisor',
    portalPath: '/panel/moren-ofis',
    apiPath: '/moren-ofis/chat',
    status: 'mobile-ready',
    priority: 'high',
    icon: Bot,
  },
  {
    id: 'ai-onay',
    title: 'AI onay kuyruğu',
    subtitle: 'Riskli işlemleri onayla, reddet veya ertele.',
    group: 'AI ekip',
    audience: 'advisor',
    portalPath: '/panel/ai-onay',
    apiPath: '/pending-actions',
    status: 'mobile-ready',
    priority: 'high',
    icon: CheckCircle2,
  },
  {
    id: 'mukellefler',
    title: 'Mükellefler',
    subtitle: 'Hızlı arama, durum ve eksik evrak görünümü.',
    group: 'Mükellef yönetimi',
    audience: 'advisor',
    portalPath: '/panel/mukellefler',
    apiPath: '/taxpayers',
    status: 'mobile-ready',
    priority: 'high',
    icon: Users,
  },
  {
    id: 'gorevler',
    title: 'Görevler',
    subtitle: 'Hatırlatmalar, gecikenler ve bugünkü işler.',
    group: 'Operasyon',
    audience: 'advisor',
    portalPath: '/panel/gorevler',
    apiPath: '/tasks',
    status: 'mobile-ready',
    priority: 'high',
    icon: ClipboardList,
  },
  {
    id: 'mobil-ocr',
    title: 'Mobil OCR tarama',
    subtitle: 'Mükellef seç, görüntü tara, portala OCR kuyruğu olarak gönder.',
    group: 'Belge',
    audience: 'advisor',
    portalPath: '/panel/fatura-isleme',
    apiPath: '/fatura-muhasebelestirme/documents/upload',
    status: 'mobile-ready',
    priority: 'high',
    icon: Camera,
  },
  {
    id: 'evraklar',
    title: 'Evraklar',
    subtitle: 'Belge arşivi, geçerlilik takibi ve yükleme.',
    group: 'Belge',
    audience: 'advisor',
    portalPath: '/panel/evraklar',
    apiPath: '/documents',
    status: 'mobile-ready',
    priority: 'high',
    icon: FolderOpen,
  },
  {
    id: 'kdv-kontrol',
    title: 'KDV kontrol',
    subtitle: 'KDV oturumları, OCR ve kontrol sonuçları.',
    group: 'Vergi',
    audience: 'advisor',
    portalPath: '/panel/kdv-kontrol',
    apiPath: '/kdv-control',
    status: 'mobile-ready',
    priority: 'high',
    icon: ShieldCheck,
  },
  {
    id: 'beyannameler',
    title: 'Beyannameler',
    subtitle: 'Beyan takip, kayıtlar ve dönem durumları.',
    group: 'Vergi',
    audience: 'advisor',
    portalPath: '/panel/beyannameler',
    apiPath: '/beyanname-takip',
    status: 'mobile-ready',
    priority: 'medium',
    icon: FileCheck2,
  },
  {
    id: 'faturalar',
    title: 'Faturalar',
    subtitle: 'E-arşiv, Mihsap ve muhasebeleştirme akışı.',
    group: 'Muhasebe',
    audience: 'advisor',
    portalPath: '/panel/fatura-isleme',
    apiPath: '/fatura-muhasebelestirme',
    status: 'mobile-ready',
    priority: 'medium',
    icon: ReceiptText,
  },
  {
    id: 'cari-kasa',
    title: 'Cari kasa',
    subtitle: 'Tahsilat, hizmet ve borç/alacak görünümü.',
    group: 'Finans',
    audience: 'advisor',
    portalPath: '/panel/cari-kasa',
    apiPath: '/cari-kasa',
    status: 'mobile-ready',
    priority: 'medium',
    icon: Banknote,
  },
  {
    id: 'banka-takip',
    title: 'Banka takip',
    subtitle: 'Ekstre kontrolü ve banka işlem durumu.',
    group: 'Finans',
    audience: 'advisor',
    portalPath: '/panel/banka-takip',
    apiPath: '/banka-takip',
    status: 'mobile-ready',
    priority: 'medium',
    icon: Landmark,
  },
  {
    id: 'mali-tablolar',
    title: 'Mali tablolar',
    subtitle: 'Mizan, gelir tablosu ve bilanço özetleri.',
    group: 'Raporlama',
    audience: 'advisor',
    portalPath: '/panel/mizan',
    apiPath: '/mizan',
    status: 'mobile-ready',
    priority: 'medium',
    icon: Scale,
  },
  {
    id: 'bordro',
    title: 'Bordro/SGK',
    subtitle: 'Personel, SGK ve bordro kontrol alanı.',
    group: 'Operasyon',
    audience: 'advisor',
    portalPath: '/panel/bordro',
    status: 'mobile-ready',
    priority: 'low',
    icon: BriefcaseBusiness,
  },
  {
    id: 'ajanlar',
    title: 'Ajanlar',
    subtitle: 'Luca, Mihsap, SGK, tebligat ve loglar.',
    group: 'Otomasyon',
    audience: 'advisor',
    portalPath: '/panel/ajanlar',
    apiPath: '/agent-events',
    status: 'mobile-ready',
    priority: 'medium',
    icon: Bot,
  },
  {
    id: 'bildirimler',
    title: 'Bildirimler',
    subtitle: 'DENİZ uyarıları ve sistem bildirimleri.',
    group: 'Ana akış',
    audience: 'advisor',
    portalPath: '/panel/bildirimler',
    apiPath: '/notifications',
    status: 'mobile-ready',
    priority: 'medium',
    icon: Bell,
  },
  {
    id: 'e-defter',
    title: 'e-Defter Kontrol',
    subtitle: 'Berat, tahakkuk tarihleri ve denetim bulguları.',
    group: 'Raporlama',
    audience: 'advisor',
    portalPath: '/panel/ajanlar/e-defter',
    apiPath: '/edefter-control',
    status: 'mobile-ready',
    priority: 'medium',
    icon: BookCheck,
  },
];

export const taxpayerModules: MobileModule[] = [
  {
    id: 'taxpayer-home',
    title: 'Mükellef özeti',
    subtitle: 'Borç/alacak, beyanname ve bekleyen evrak.',
    group: 'Ana akış',
    audience: 'taxpayer',
    apiPath: '/mobile/bootstrap?audience=taxpayer',
    status: 'mobile-ready',
    priority: 'high',
    icon: Building2,
  },
  {
    id: 'taxpayer-upload',
    title: 'Evrak gönder',
    subtitle: 'Fatura, dekont ve belgeleri kameradan yükle.',
    group: 'Belge',
    audience: 'taxpayer',
    apiPath: '/documents/upload/initiate',
    status: 'mobile-ready',
    priority: 'high',
    icon: UploadCloud,
  },
  {
    id: 'taxpayer-docs',
    title: 'Belgelerim',
    subtitle: 'Beyanname, tahakkuk, mizan ve rapor arşivi.',
    group: 'Belge',
    audience: 'taxpayer',
    apiPath: '/documents/taxpayer/:id',
    status: 'mobile-ready',
    priority: 'high',
    icon: FileArchive,
  },
  {
    id: 'taxpayer-kdv',
    title: 'KDV durumu',
    subtitle: 'Bu dönem için hazırlık ve mutabakat durumu.',
    group: 'Vergi',
    audience: 'taxpayer',
    apiPath: '/taxpayers/:id/monthly-status',
    status: 'mobile-ready',
    priority: 'high',
    icon: ShieldCheck,
  },
  {
    id: 'taxpayer-declarations',
    title: 'Beyannamelerim',
    subtitle: 'Beyanname ve tahakkuk PDF erişimi.',
    group: 'Vergi',
    audience: 'taxpayer',
    apiPath: '/beyan-kayitlari',
    status: 'mobile-ready',
    priority: 'medium',
    icon: FileText,
  },
  {
    id: 'taxpayer-faturalar',
    title: 'Faturalarım',
    subtitle: 'Alış/satış faturaları ve PDF erişimi.',
    group: 'Vergi',
    audience: 'taxpayer',
    apiPath: '/portal/faturalar',
    status: 'mobile-ready',
    priority: 'medium',
    icon: ReceiptText,
  },
  {
    id: 'taxpayer-current',
    title: 'Cari hesabım',
    subtitle: 'Ödeme, tahsilat ve açık bakiye özeti.',
    group: 'Finans',
    audience: 'taxpayer',
    apiPath: '/portal/cari',
    status: 'mobile-ready',
    priority: 'medium',
    icon: Banknote,
  },
  {
    id: 'taxpayer-tebligat',
    title: 'e-Tebligat',
    subtitle: 'Resmi tebligatlar ve okundu durumu.',
    group: 'Resmi',
    audience: 'taxpayer',
    apiPath: '/portal/tebligatlar',
    status: 'mobile-ready',
    priority: 'medium',
    icon: Inbox,
  },
  {
    id: 'taxpayer-sgk',
    title: 'SGK belgeleri',
    subtitle: 'Prim tahakkuku ve aylık bildirgeler.',
    group: 'Resmi',
    audience: 'taxpayer',
    apiPath: '/portal/sgk',
    status: 'mobile-ready',
    priority: 'medium',
    icon: BriefcaseBusiness,
  },
  {
    id: 'taxpayer-message',
    title: 'Ofise mesaj',
    subtitle: 'Soru, randevu ve evrak notu gönder.',
    group: 'İletişim',
    audience: 'taxpayer',
    apiPath: '/pending-actions',
    status: 'mobile-ready',
    priority: 'high',
    icon: Mail,
  },
  {
    id: 'taxpayer-calendar',
    title: 'Takvim',
    subtitle: 'Son tarih, evrak teslim ve randevu günleri.',
    group: 'İletişim',
    audience: 'taxpayer',
    apiPath: '/tasks',
    status: 'mobile-ready',
    priority: 'medium',
    icon: CalendarCheck,
  },
];

/** Modül kimliği -> ekran rotası + portal imzası rengi */
export const moduleNav: Record<string, { route: string; color: ModuleColor }> = {
  // --- müşavir ---
  dashboard: { route: '/(advisor)', color: 'gold' },
  'moren-ofis': { route: '/(advisor)/ofis', color: 'rose' },
  'ai-onay': { route: '/(advisor)/onay', color: 'rose' },
  mukellefler: { route: '/(advisor)/mukellefler', color: 'gold' },
  gorevler: { route: '/(advisor)/gorevler', color: 'gold' },
  'mobil-ocr': { route: '/(advisor)/ocr', color: 'sage' },
  evraklar: { route: '/(advisor)/evraklar', color: 'copper' },
  'kdv-kontrol': { route: '/(advisor)/kdv-kontrol', color: 'amber' },
  beyannameler: { route: '/(advisor)/beyannameler', color: 'amber' },
  faturalar: { route: '/(advisor)/fatura-merkezi', color: 'sage' },
  'cari-kasa': { route: '/(advisor)/cari-kasa', color: 'copper' },
  'banka-takip': { route: '/(advisor)/banka-takip', color: 'copper' },
  'mali-tablolar': { route: '/(advisor)/mali-tablolar', color: 'blue' },
  bordro: { route: '/(advisor)/sgk', color: 'steel' },
  ajanlar: { route: '/(advisor)/ajanlar', color: 'steel' },
  bildirimler: { route: '/(advisor)/bildirimler', color: 'rose' },
  'e-defter': { route: '/(advisor)/e-defter', color: 'blue' },
  // --- mükellef ---
  'taxpayer-home': { route: '/(taxpayer)', color: 'blue' },
  'taxpayer-upload': { route: '/(taxpayer)/evrak', color: 'gold' },
  'taxpayer-docs': { route: '/(taxpayer)/belgeler', color: 'blue' },
  'taxpayer-kdv': { route: '/(taxpayer)/kdv', color: 'amber' },
  'taxpayer-declarations': { route: '/(taxpayer)/beyannameler', color: 'amber' },
  'taxpayer-faturalar': { route: '/(taxpayer)/faturalar', color: 'sage' },
  'taxpayer-current': { route: '/(taxpayer)/cari', color: 'copper' },
  'taxpayer-tebligat': { route: '/(taxpayer)/tebligat', color: 'blue' },
  'taxpayer-sgk': { route: '/(taxpayer)/sgk', color: 'steel' },
  'taxpayer-message': { route: '/(taxpayer)/mesaj', color: 'copper' },
  'taxpayer-calendar': { route: '/(taxpayer)/takvim', color: 'steel' },
};

export function getModuleNav(id: string): { route: string; color: ModuleColor } {
  return moduleNav[id] || { route: '/(advisor)', color: 'gold' };
}

export const moduleCatalog = {
  advisor: advisorModules,
  taxpayer: taxpayerModules,
};

export function getModulesForAudience(audience: AppAudience) {
  return moduleCatalog[audience];
}

export function groupModules(modules: MobileModule[]) {
  return modules.reduce<Record<string, MobileModule[]>>((acc, module) => {
    acc[module.group] = acc[module.group] || [];
    acc[module.group].push(module);
    return acc;
  }, {});
}
